teleportDelay: 2.5
spinPlayerOnTeleport: true
teleportPlayerDamageFraction: 0.25
dropItemsOnDamageWhileSpinning: true
removeMarkAfterTeleport: true
teleportRequireFreeSpot: false
notMarkable:
  - PISTON_EXTENSION
  - FENCE
  - FENCE_GATE
  - WOOD_DOOR
  - IRON_DOOR
  - COBBLE_WALL
  - WOODEN_DOOR
factionsAllowMarkingInWarzone: true
factionsAllowMarkingInSafezone: true
factionsAllowMarkingInWilderness: true