name: EnderPearlRevamp

main: clavus.enderpearlrevamp.EnderPearlRevamp

version: 1.5

commands:
   epr:
      description: Controls EnderPearlRevamp
      usage: |
           /<command> reload - reloads plugin config